# Site settings
title: Startup the Woo
email: startupthewoo@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Community curated resources for entrepreneurs in Worcester! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://startupthewoo.org" # the base hostname & protocol for your site
github_username:  startupthewoo

# Build settings
markdown: kramdown
